server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:./data/articlesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

branch:
  name: Medellin
