server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/configurations

management:
  endpoints:
    web:
      exposure:
        include: health,info
