server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    config:
      fail-fast: false
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}