server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    config:
      fail-fast: false
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}