server:
  port: 8082

spring:
  application:
    name: articles-service
  cloud:
    config:
      fail-fast: false
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}